# Generated by Django 3.1.7 on 2021-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210531_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
